backend:
  name: github
  repo: cooltable/eastside-swim-school

media_folder: static/assets
public_folder: assets

collections:
  - name: testimonial
    label: Testimonial
    folder: testimonials
    create: true
    fields:
      - { name: title, label: Name }
      - { name: body, label: Testimonial, widget: text }
  - name: announcement
    label: Announcement
    folder: announcements
    create: true
    fields:
      - { name: title, label: Title }
      - { name: body, label: Announcement, widget: markdown }
  - name: class
    label: Class
    folder: classes
    create: true
    fields:
      - name: title
        label: Title
      - name: link
        label: Link
        required: false
      - name: classPeriods
        label: Class Periods
        widget: list
        required: false
        fields:
          - label: Date Range
            name: dateRange
            widget: list
            fields:
              - widget: date
                label: Start Date
                name: startDate
                default: ""
                format: MMM Do YY
                timeFormat: true
              - widget: date
                label: End Date
                name: endDate
                default: ""
                format: MMM Do YY
                timeFormat: true
          - name: days
            label: 'Days of the week'
            widget: select
            multiple: true
            options:
              [
              'Sunday',
              'Monday',
              'Tuesday',
              'Wednesday',
              'Thursday',
              'Friday',
              'Saturday',
              ]
            required: false
          - name: classesCount
            label: Classes Count
            required: false
            widget: number
          - name: times
            label: Times
            widget: list
            required: false
            fields:
              - name: time
                label: Time
                widget: string
              - name: available
                label: Has Openings
                widget: boolean
                default: false
      - { name: body, label: Description, widget: markdown }
      - {
          name: ageGroup,
          label: 'Age Group',
          widget: select,
          options: ['Baby', 'Preschool', 'Grade School', 'Pre Comp', 'Adult'],
        }
      - {
          name: difficulty,
          label: Difficulty,
          widget: select,
          options: ['1', '2', '3'],
        }
      - { name: thumbnail, label: 'Featured Image', widget: 'image' }
  - name: coaches
    label: Coaches
    folder: coaches
    create: true
    fields:
      - { name: title, label: Name }
      - {
          name: order,
          label: Ranking,
          widget: select,
          options: ['1', '2', '3', '4', '5', '6', '7', '8'],
        }
      - { name: oneStudent, label: 'One Student', required: false }
      - { name: twoStudents, label: 'Two Students', required: false }
      - { name: thumbnail, label: 'Featured Image', widget: 'image', required: false }
      - { name: link, label: 'Link to site' }
      - { name: body, label: "Bio", widget: "text"}
  - name: pages
    label: Pages
    folder: pages
    create: true
    fields:
      - {label: Title, name: "title", widget: "string"}
      - {label: Url, name: path, widget: "string"}
      - { label: Page Body, name: 'body', widget: 'markdown' }


