backend:
  name: github
  repo: cooltable/eastside-swim-school

media_folder: static/assets
public_folder: assets

collections:
  - name: testimonial
    label: Testimonial
    folder: testimonials
    create: true
    fields:
      - { name: title, label: Name }
      - { name: body, label: Testimonial, widget: text }
  - name: announcement
    label: Announcement
    folder: announcements
    create: true
    fields:
      - { name: title, label: Title }
      - { name: body, label: Announcement, widget: markdown }
  - name: class
    label: Class
    folder: classes
    create: true
    fields:
      - { name: title, label: Title }
      - { name: time, label: Time, required: false }
      - {
          name: day,
          label: 'Day of the week',
          widget: select,
          options:
            [
              'Sunday',
              'Monday',
              'Tuesday',
              'Wednesday',
              'Thursday',
              'Friday',
              'Saturday',
            ],
            required: false
        }
      - { name: time2, label: 'Time 2 *optional', required: false }
      - {
          name: day2,
          label: 'Day of the week 2 *optional',
          widget: select,
          options:
            [
              'Sunday',
              'Monday',
              'Tuesday',
              'Wednesday',
              'Thursday',
              'Friday',
              'Saturday',
            ],
          required: false
        }
      - { name: time3, label: 'Time 3 *optional', required: false }
      - {
          name: day3,
          label: 'Day of the week 3 *optional',
          widget: select,
          options:
            [
              'Sunday',
              'Monday',
              'Tuesday',
              'Wednesday',
              'Thursday',
              'Friday',
              'Saturday',
            ],
          required: false
        }
      - { name: time4, label: 'Time 4 *optional', required: false }
      - {
          name: day4,
          label: 'Day of the week 4 *optional',
          widget: select,
          options:
            [
              'Sunday',
              'Monday',
              'Tuesday',
              'Wednesday',
              'Thursday',
              'Friday',
              'Saturday',
            ],
          required: false
        }
        - { name: time5, label: 'Time 5 *optional', required: false }
      - {
          name: day5,
          label: 'Day of the week 5 *optional',
          widget: select,
          options:
            [
              'Sunday',
              'Monday',
              'Tuesday',
              'Wednesday',
              'Thursday',
              'Friday',
              'Saturday',
            ],
          required: false
        }
      - { name: body, label: Description, widget: markdown }
      - {
          name: ageGroup,
          label: 'Age Group',
          widget: select,
          options: ['Preschool', 'Grade School', 'Pre Comp', 'Adult'],
        }
      - {
          name: difficulty,
          label: Difficulty,
          widget: select,
          options: ['1', '2', '3'],
        }
      - { name: thumbnail, label: 'Featured Image', widget: 'image' }
      - { name: link, label: 'Link to site' }
  - name: coaches
    label: Coaches
    folder: coaches
    create: true
    fields:
      - { name: title, label: Name }
      - { name: oneStudent, label: 'One Student', required: false }
      - { name: twoStudents, label: 'Two Students', required: false }
      - { name: thumbnail, label: 'Featured Image', widget: 'image' }
      - { name: link, label: 'Link to site' }
      - { name: body, label: "Bio", widget: "text"}
